language: java

script:
  - mvn test -B

jdk:
  - oraclejdk8

cache:
  directories:
    - '$HOME/.m2/repositories'
    - '$HOME/.sonar/cache'

after_success:
  - bash <(curl -s https://codecov.io/bash)